### ISSUE TITLE
Add CI to build and release package to central repo

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-jdbc#13]

**Comment by Young-Flash** [comment]
I want to publish a maven package into Maven Central Repository  automatically by GitHub Action when I draft a new release. nebula-java do it with [samuelmeuli/action-maven-publish](https://github.com/samuelmeuli/action-maven-publish), `secrets.GPG_PRIVATE_KEY`, `secrets.GPG_PASSPHRASE`, `secrets.OSSRH_USERNAME`, `secrets.OSSRH_TOKEN` of vesoft need to be set in this repo, can you help me set them in Settings->Secrets->Actios->Repository secrets ?

**Comment by wey-gu** [comment]
I am terribly sorry that I missed your response, I was expecting others to help with this.
You rock @Young-Flash !
I will come back with needed permission and information on this and ping you afterwards.
Thanks!

**Comment by Young-Flash** [comment]
OK :)

**Comment by wey-gu** [comment]
update, we will register a new domain name for maven instead of using the vesoft's one, it will take some times.

**Comment by wey-gu** [comment]
update, it's pending on https://issues.sonatype.org/browse/OSSRH-80085

**Comment by wey-gu** [comment]
@Young-Flash now the above 4 variables were set properly.
Plz be noted we need to use org.nebula-contrib instead of com.vesoft :)

The release artifact site is: http://s01.oss.sonatype.org/

**Comment by Young-Flash** [comment]
okay

**Comment by Young-Flash** [comment]
@wey-gu  seems somethings wrong about the secret key [here](https://github.com/nebula-contrib/nebula-jdbc/runs/6190316080?check_suite_focus=true#step:4:1567)

**Comment by wey-gu** [comment]
I will look into it tomorrow.

**Comment by wey-gu** [comment]
@Young-Flash , it seems to be ok now 
https://github.com/nebula-contrib/nebula-jdbc/runs/6204454423?check_suite_focus=true

Thanks!!!!!

**Comment by Young-Flash** [comment]
great! so what is the problem? wrong name for secret key variables?

**Comment by wey-gu** [comment]
> great! so what is the problem? wrong name for secret key variables?

I felt so ashamed, I provided the wrong key rather than the one in gh actions, yet, I didn't put the public key to keys.openpgp.org, luckily I fixed it in one go per each issues :-P

**Comment by wey-gu** [comment]
I can see it from the repo in https://s01.oss.sonatype.org/ , does this mean user to put it in the pom.xml will fetch the nebula-jbdc?

**Comment by Young-Flash** [comment]
> I can see it from the repo in https://s01.oss.sonatype.org/ , does this mean user to put it in the pom.xml will fetch the nebula-jbdc?

yes, but we need to wait till it appears [here](https://search.maven.org/search?q=nebula-jdbc)

**Comment by wey-gu** [comment]
> 

Aha, got it :)

**Comment by Young-Flash** [comment]
now we can import nebula-jdbc into project via adding this in pom.xml
```xml
<dependency>
  <groupId>org.nebula-contrib</groupId>
  <artifactId>nebula-jdbc</artifactId>
  <version>3.0.0</version>
</dependency>
```
