### ISSUE TITLE
connect error:"No extra connection: All servers are broken."

### ISSUE THREAD

**Issue by mathlpz** [vesoft-inc/nebula-jdbc#18]
when use java-client version: 2.5.0, the server is ok!
but update nebula-jdbc, use java-client: 2.6.2, it print error info:
`com.vesoft.nebula.client.graph.exception.NotValidConnectionException: No extra connection: All servers are broken.
        at com.vesoft.nebula.client.graph.net.NebulaPool.getConnection(NebulaPool.java:215)
        at com.vesoft.nebula.client.graph.net.NebulaPool.getSession(NebulaPool.java:137)`

**Comment by Young-Flash** [comment]
what is your jdbc version and server version? make sure they are match, see [here](https://github.com/nebula-contrib/nebula-jdbc#readme).

**Comment by mathlpz** [comment]
3q, it's the version mismatch problem, the graph version is 2.5.1.
the error is miss when graph upgrade to 2.6.2.
