### ISSUE TITLE
How to introduce nebula jdbc into maven

### ISSUE THREAD

**Issue by chenhuan1204** [vesoft-inc/nebula-jdbc#26]
How to introduce nebula jdbc into maven

**Comment by Young-Flash** [comment]
Not supported now because we haven't publish it on Maven Central Repository, but it is in progress. see #13 @wey-gu

**Comment by wey-gu** [comment]
> Not supported now because we haven't publish it on Maven Central Repository, but it is in progress. see #13 @wey-gu

will provide the needed credentials/info today.

**Comment by Young-Flash** [comment]
@chenhuan1204 
```xml
<dependency>
  <groupId>org.nebula-contrib</groupId>
  <artifactId>nebula-jdbc</artifactId>
  <version>3.0.0</version>
</dependency>
```
