### ISSUE TITLE
 Please update the 3.0.0 version maven source

### ISSUE THREAD

**Issue by type-s** [vesoft-inc/nebula-jdbc#49]

**Comment by wey-gu** [comment]
it's already there, is there anything else we should update?

https://central.sonatype.dev/artifact/org.nebula-contrib/nebula-jdbc/3.0.0/

@Young-Flash @Nicole00 shall we do another release with the latest stable nebula-java now?

**Comment by Young-Flash** [comment]
Agree. Is [release-3.3](https://github.com/vesoft-inc/nebula-java/tree/release-3.3) the latest stable nebula-java  now ？and how to name the version of nebula-jdbc? 3.3 too ？

**Comment by wey-gu** [comment]
> Agree. Is [release-3.3](https://github.com/vesoft-inc/nebula-java/tree/release-3.3) the latest stable nebula-java now ？and how to name the version of nebula-jdbc? 3.3 too ？

Yes, I think so, VerName of 3.3.0 looks good to me :D

https://central.sonatype.dev/artifact/com.vesoft/client/3.3.0

**Comment by Young-Flash** [comment]
v3.3.0 have been published to maven, can been see [here](https://central.sonatype.dev/artifact/org.nebula-contrib/nebula-jdbc/3.3.0/overview).
