### ISSUE TITLE
datetime时间参数set问题

### ISSUE THREAD

**Issue by charle004** [vesoft-inc/nebula-jdbc#58]
3.3.0没有发现 示例代码的 setDateTime方法，于是我将nebula中的时间改成了 int64类型，准备存储时间戳，但是setLong 目前提示我 not support，所以目前如何set nebula中的 datetime类型呢？

**Comment by Young-Flash** [comment]
see https://github.com/nebula-contrib/nebula-jdbc/blob/0e9f86762ad85710f0c39ad8f9d9ef9b8a26243f/src/main/java/com/vesoft/nebula/jdbc/statement/NebulaPreparedStatementImpl.java#L140
