### ISSUE TITLE
字符串中出现' "之类的字符时 导致insert失败

### ISSUE THREAD

**Issue by charle004** [vesoft-inc/nebula-jdbc#59]

**Comment by Young-Flash** [comment]
加上转义 \ 试试

**Comment by charle004** [comment]
> 加上转义 \ 试试

insert 的语句手动加上执行是没问题的，我是在利用 NebulaPreparedStatement  设置参数后execute 出现这个错误的，后续能否在参数设置内部加上兼容处理呢

**Comment by Young-Flash** [comment]
建议在传入前先做处理

**Comment by charle004** [comment]
> 

能否在内部做转义处理呢？因为数据中出现特殊字符的几率挺高的，无法全部手动作处理
